// Generated by CoffeeScript 1.8.0
(function() {
  var _;

  _ = require('underscore');

  exports.isDirectory = function(path) {
    return (path.slice(-1)) === '/';
  };

  exports.traverse = function(obj, path) {
    var segment, _i, _len, _ref;
    if (path == null) {
      path = '';
    }
    _ref = _.compact(path.split('.'));
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      segment = _ref[_i];
      obj = obj[segment];
    }
    return obj;
  };

  exports.set = function(obj, path, value) {
    var segment, segments, sub;
    sub = obj;
    segments = _.compact(path.split('.'));
    while (segment = segments.shift()) {
      if (segments.length > 1) {
        sub = sub[segment] != null ? sub[segment] : sub[segment] = {};
      } else {
        sub[segment] = value;
      }
    }
    return obj;
  };

  exports.namespace = function(path) {
    if (path) {
      return _.partial(exports.set, _, path);
    } else {
      return _.extend;
    }
  };

  exports.kv = function(key, value) {
    var wrapped;
    wrapped = {};
    wrapped[key] = value;
    return wrapped;
  };

  exports.string = {
    unwrap: function(str) {
      return str.replace(/\W?\n/g, ' ');
    }
  };

}).call(this);
